### ISSUE TITLE
Address validation in MacOS

### ISSUE THREAD

**Issue by cyclemaxwell** [JanCBrammer/OpenHRV#26]
Bluetooth address validation fails on MacOS when the `connect` button is pressed. The address returned by the `QBluetoothDeviceInfo.address()` function is all zeros.

**Comment by JanCBrammer** [comment]
I suspect I took the regex from this SO post (can't say for sure though): https://stackoverflow.com/questions/7905929/how-to-test-valid-uuid-guid.

The regex should capture UUIDs according to the [RFC 4122 specification](https://www.rfc-editor.org/rfc/rfc4122), which should be compatible with the [format](https://developer.apple.com/documentation/foundation/nsuuid) that Apple devices seem to use when [interacting with Bluetooth peripherals](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW1).

**Comment by JanCBrammer** [comment]
> checks the platform and selects whether to request the address or the uuid

Nice. Posting the respective Qt docs here for future reference: https://doc.qt.io/qt-6/qbluetoothdeviceinfo.html#address

**Comment by JanCBrammer** [comment]
> This replaces use of the `.address()` method.

The call to `.address()` needs to be replaced here as well:
https://github.com/JanCBrammer/OpenHRV/blob/89eef2c19e95879b73385a5076bfde307aa4e8c6/openhrv/model.py#L63

**Comment by cyclemaxwell** [comment]
Nice. I guess this means implementing a second utility function `get_remote_address_or_uuid(client)`

**Comment by cyclemaxwell** [comment]
> The regex should capture UUIDs according to the [RFC 4122 specification](https://www.rfc-editor.org/rfc/rfc4122), which should be compatible with the [format](https://developer.apple.com/documentation/foundation/nsuuid) that Apple devices seem to use when [interacting with Bluetooth peripherals](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/BestPracticesForInteractingWithARemotePeripheralDevice/BestPracticesForInteractingWithARemotePeripheralDevice.html#//apple_ref/doc/uid/TP40013257-CH6-SW1).

As far as I can tell, my H10 is returning a non-compliant uuid. (second to last grouping begins with `e`) of the form:
XXXXXXXX-XXXX-4XXX-eXXX-XXXXXXXXXXXX

Is there a reason to require that the uuid be compliant with standards. Would it be ok to simply require a pseudo-UUID to be formatted with the correct number of hex characters and dashes?

**Comment by mirkancal** [comment]
I'm also on MacOS with Polar H10. I can see my device but can't connect.

Invalid sensor address: cd818013-47f2-e83e-dc7c-05f6a924a5ad.
