### ISSUE TITLE
Polar H9 not found due to zero RSSI

### ISSUE THREAD

**Issue by mlichvar** [JanCBrammer/OpenHRV#35]
I have paired a Polar H9 sensor to my laptop running bluez 5.71 with Intel AX201 wifi+bluetooth chipset, but OpenHRV doesn't show it when I press "Scan". After some debugging it seems the issue is that the RSSI is reported as 0, which is ignored in the code. There is a comment "TODO: comment why rssi needs to be negative". I'm not sure what is the reason behind it, but at least in my case it doesn't work. When I change it to accept 0, everything seems to be working fine.

**Comment by JanCBrammer** [comment]
@mlcihvar, thanks for reporting this! I made a mistake, the accepted range should *include* `0`, i.e., `<= 0` (see https://www.bluetooth.com/blog/proximity-and-rssi/, https://www.mokoblue.com/measures-of-bluetooth-rssi/). Do you want to open a PR?

**Comment by JanCBrammer** [comment]
Makes sense, thanks again for the issue.

**Comment by JanCBrammer** [comment]
Closing with 32d0f7f585905ac8d1837cdfb34aa75cb8d5f1b9.
